---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/test.yaml
      - "**.go"
      - "go.mod"
      - "go.sum"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with: { go-version-file: go.mod }

      - name: Run tests
        run: go test -v ./... -race -covermode=atomic
