---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Trivy

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        required: false
        default: false
        type: boolean

  pull_request:
    paths: [ ".github/workflows/trivy-scan.yaml" ]

  schedule:
    - cron: "1 0 * * *"

permissions:
  security-events: write
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Create directory for scan results
        run: mkdir -p trivy-results

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
        with:
          image-ref: ghcr.io/mirceanton/external-dns-provider-mikrotik:latest
          format: 'sarif'
          output: 'trivy-results/results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          ignore-unfixed: false
          vuln-type: 'os,library'

      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ !(inputs.dry-run || github.event_name == 'pull_request') }}
        uses: github/codeql-action/upload-sarif@28deaeda66b76a05916b6923827895f2b14ab387 # v3.28.16
        with:
          sarif_file: 'trivy-results/results.sarif'
          category: 'trivy'
